BG_MAIN_COLOR = '#FFFFFF'
BG_PLAYERS_SPACE = '#B7CBFF'
BG_PLAYERS_NAME = '#4557F1'
BG_PLAYERS_SCORE = '#4557F1'
BG_BOARD_POSITIONS = '#CACAC6'
BG_PACKS_POSITIONS = '#152931'

FONT_SCORE_TITLE = ('Noto Sans', 16)
FONT_SCORE_NUMBER = ('Noto Sans', 20)
FONT_PLAYERS_NAMES = ('Noto Sans', 12)

INITIAL_PLAYER_NAME = 'Player name goes here'